### ISSUE TITLE
Push Notification to OS

### ISSUE THREAD

**Issue by ProPheT777** [jolicode/JoliCi#44]
Personally when I run test, I minimize the terminal and forget it (for a little time). Push notification to the OS notification center can be a really useful feature. 

Here an example for Linux ubuntu based : 

```shell
notify-send "JoliCI Test passed on php 5.4" -i "/usr/share/icons/gnome/32x32/emblems/emblem-default.png" 
```

![capture du 2015-02-05 14 20 13](https://cloud.githubusercontent.com/assets/1763341/6060857/1dd97eaa-ad42-11e4-9670-41e08c06180f.png)

Ubuntu Notify OSD https://wiki.ubuntu.com/NotifyOSD
Package linux : notify-osd

An equivalent system exist also for Mac user.

**Comment by joelwurtz** [comment]
For the moment notifications are not planned for JoliCi, in the meantime i will try to give information in documentation to pipe jolici process with a notification system 

(This could be done easily by testing the return type of jolici process as it return 0 on success and the number of failed test otherwise, like `(php jolici.phar && notify 'Test Pass') || notify 'Test failed'`

**Comment by joelwurtz** [comment]
I add the notifications in the last release, thanks for the idea :)

**Comment by ProPheT777** [comment]
:beers:
