### ISSUE TITLE
Can't run on cpp project

### ISSUE THREAD

**Issue by kpp** [jolicode/JoliCi#50]
Is it possible to run [cpp project](llst.org)?

```
humbug@work ~/llst $ php jolici.phar run
Creating builds...
PHP Notice:  Undefined index: cpp in phar:///home/humbug/llst/jolici.phar/src/Joli/JoliCi/BuildStrategy/TravisCiBuildStrategy.php on line 271
PHP Warning:  Invalid argument supplied for foreach() in phar:///home/humbug/llst/jolici.phar/src/Joli/JoliCi/BuildStrategy/TravisCiBuildStrategy.php on line 273
PHP Catchable fatal error:  Argument 2 passed to Joli\JoliCi\Matrix::setDimension() must be of the type array, null given, called in phar:///home/humbug/llst/jolici.phar/src/Joli/JoliCi/BuildStrategy/TravisCiBuildStrategy.php on line 303 and defined in phar:///home/humbug/llst/jolici.phar/src/Joli/JoliCi/Matrix.php on line 26
humbug@work ~/llst $ travis lint
Hooray, .travis.yml looks valid :)
humbug@work ~/llst $ php -v
PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:47:39) 
```

**Comment by joelwurtz** [comment]
Sorry but only ruby, node and php languages are currently supported, so no cpp :/

If you want to add the images to this repository https://github.com/jolicode/docker-images (or an other one, this just need to be close to a travis ci environment, and i recommend to start of jolicode/base image as you will have the basic tool that travis ci need) in order to mimic travis ci environnement i will be glad to add the support of it.

**Comment by lyrixx** [comment]
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.
